version: "2"
services:
  frontend:
    build: ./front
    command: serve
    env_file:
      - ./env/front/dev.env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./front/package.json:/app/package.json
      - ./front/node_modules:/app/node_modules
      - ./front/dist:/app/dist
      - ./front/public:/app/public
      - ./front/src:/app/src
      - ./front/tsconfig.json:/app/tsconfig.json
